### ISSUE TITLE
[Zephyr] # CONFIG_IS_BOOTLOADER is not set

### ISSUE THREAD

**Issue by SebastianBoe** [runtimeco/mcuboot#230] opened 2018-02-12 12:56 UTC
Hi,

when following the instructions for building a Zephyr bootloader I was surprised to see that in the .config:

`# CONFIG_IS_BOOTLOADER is not set`

Is this a bug?

**Comment by SebastianBoe** [comment] 2018-02-12 12:57
Steps to reproduce:

Build ~/mcuboot/boot/zephyr with BOARD nrf52_pca10040.

grep IS_BOOT ~/mcuboot/boot/zephyr/build/zephyr/.config

**Comment by carlescufi** [comment] 2018-02-12 15:02
No, this is not a bug. `CONFIG_IS_BOOTLOADER` is essentially a hack. We do not want cross-dependencies between Zephyr and MCUboot. Instead we only want MCUboot to be able to configure Zephyr to meet its requirements. If anything what we need to do is to get rid or rename `CONFIG_IS_BOOTLOADER`.

**Comment by carlescufi** [comment] 2018-02-12 15:05
@utzig we can close this.

**Closed** 2018-02-12 15:55 UTC

**Comment by SebastianBoe** [comment] 2018-02-13 07:53
okay ...

then we definitely need to improve the documentation here:

```
config IS_BOOTLOADER
	bool "Act as a bootloader"
	default n
	depends on XIP
	depends on ARM
	help
	  This option indicates that Zephyr will act as a bootloader to execute
	  a separate Zephyr image payload.


```

When is IS_BOOTLOADER supposed to be enabled/disabled?

**Comment by mbolivar** [comment] 2018-02-13 14:29
CONFIG_IS_BOOTLOADER's purpose is to set aside an area of SRAM for use by Zephyr. Perhaps that is useful on some bootloaders if they need to keep their state after passing control to the application. But I think this is not necessary on mcuboot, which does not need any state preserved after passing control to Zephyr. (We discussed passing some mcuboot state to Zephyr a while ago on the developer list, but this is not a supported feature now.)

**Comment by SebastianBoe** [comment] 2018-02-13 14:33
Right, so maybe,

CONFIG_RESERVE_RAM_FOR_BOOTLOADER

or something. Because obviously it is possible to be a bootloader, and not need RAM reserved.
I would suggest that this issue is re-opened with a different title.

**Comment by mbolivar** [comment] 2018-02-13 14:35
That's a Zephyr issue, not an MCUboot one

**Comment by SebastianBoe** [comment] 2018-02-13 14:36
My mistake.
